# Generated by Django 2.0.5 on 2018-05-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submissions', models.IntegerField(default=0, editable=False)),
                ('videolink', models.CharField(max_length=100)),
                ('video_id', models.TextField(default='8tPnX7OPo0Q', editable=False)),
                ('domain', models.CharField(default='Enter domain', max_length=20)),
                ('title', models.TextField(default='Only change if you want to edit, Will fetch from youtube')),
                ('description', models.TextField(default='Only change if you want to edit, Will fetch from youtube')),
                ('time_to_show', models.TextField(default='Only change if you want to edit, Will fetch from youtube')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
