# Generated by Django 2.0.5 on 2018-05-24 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problemstatements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_indivisual', models.BooleanField()),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problemStatement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemstatements.ProblemStatement')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General', 'General'), ('Advanced', 'Advanced'), ('Legendary', 'Legendary')], default='General', max_length=10)),
                ('selected', models.BooleanField(default=False)),
                ('is_team', models.BooleanField(default=False)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(default='Default', max_length=100, null=True)),
                ('video_solution', models.CharField(default='default', max_length=100)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problemStatement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemstatements.ProblemStatement')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_indivisual', models.BooleanField()),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('problemStatement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemstatements.ProblemStatement')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sponsor',
            unique_together={('sponsor', 'problemStatement')},
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('contestant', 'problemStatement')},
        ),
        migrations.AlterUniqueTogether(
            name='mentor',
            unique_together={('mentor', 'problemStatement')},
        ),
    ]
