# Generated by Django 2.0.5 on 2018-06-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0003_auto_20180605_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatementPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=100)),
                ('playlist_url', models.CharField(max_length=100)),
            ],
        ),
    ]
