# Generated by Django 2.0.5 on 2018-06-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0004_problemstatementplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='is_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='is_older',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='is_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='is_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='is_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problemstatementplaylist',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='problemstatementplaylist',
            name='playlist_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
