# Generated by Django 2.0.4 on 2018-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0004_auto_20180508_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatement',
            name='contents',
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='time_to_show',
            field=models.TextField(default='8 years ago'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='description',
            field=models.TextField(default='The Muppet’s Musical Gang is back at it with their rendition of Queen’s Bohemian Rhapsody!\nSubscribe for all new videos from The Muppets! ► http://www.youtube.com/subscription_center?add_user=MuppetsStudios \nWatch more Muppet Music Videos► https://www.youtube.com/playlist?list=PLiyHgXXaitUHx0Jpt9tW1k0ZZuydnNORl\n\nGet ready for “The Muppets” like you’ve never seen them before! Watch the brand new series on Tuesday nights at 8/9p Central, only on ABC!\nWatch the best moments from the Muppets on ABC! ►http://bit.ly/1h7TqDN\n\nInspired by one off the all time greats, QUEEN, the Muppets present their rendition of the classic, "Bohemian Rhapsody." Originally released in 1975, this classic with a Muppets Twist is sure to keep every music lover, and Muppet fan satisfied. \nWatch more of the best moments, music videos, and laughs from The Muppets! ► https://www.youtube.com/playlist?list=PLiyHgXXaitUEgAKvEzfsV1GTgJnrcy0j3\n\nGet more from The Muppets!\nhttp://disney.com/muppets\nFacebook: https://www.facebook.com/Muppets\nTwitter: http://www.twitter.com/MuppetsStudio\nTumblr: http://themuppets.tumblr.com\nInstagram: http://www.instagram.com/themuppets\n\nMuppets Characters\nGonzo is a multi-talented artist who performs outrageous daredevil stunts. Though an odd looking creature, Gonzo takes pride in his uniqueness and enjoys every adventure he goes on with the Muppets including the occasional space voyage. \n\nRowlf the Dog is the Muppet’s resident piano player. One of the Muppets oldest characters, Rowlf rose to stardom by first plugging advertisements for his favorite dog-food brands on the original Muppets show. Rowlf the Dog is not the trusty Muppets sidekick  always ready to help Kermit the Frog, Fozzie Bear, Miss Piggy, and the rest of the Muppets. \n\nAnimal is the wild drummer for the almost-legendary band, Dr. Teeth and The Electric Mayhem, who are the regular performers traveling with the Muppets. Animal is the official musical Muppet. Known for his outrageous style and unclear speaking voice, Animal is a crazed percussionist with three music style - loud, louder and loudest.\n\nPepe the King Prawn, lovingly known as Pepe, comes to the Muppets from Spain. Pepe moved to Hollywood to pursue his one true calling show business. Peep’s strong spanish accent makes it difficult for him to be understood.\n\nNot one to leave the Muppet Lab too often, Beaker is the accident-prone assistant to Dr. Bunsen Honeydew. Though often difficult to understand, due to his “Meep”, Beaker is known among the Muppets as the one who always gets hurt. \n\nWhen the Muppets made it big, they needed to hire a fool-proof security guard. Thus, Bobo the Bear became head of Muppets security. \n\nDr. Bunsen Honeydew and his assistant Beaker are the resident scientists of the Muppets experimenting away in the Muppets Lab. Bunsen is always eager to show off his latest scientific discoveries to the Muppets. \n\nFozzie Bear is the world’s funniest—and only— stand-up comedy bear. From his beat-up hat to the “wocka wocka” that punctuates his punchlines, Fozzie is an “old school” comic. His jokes aren’t always great, but they are delivered with heart and Fozzie’s signature pazazz. \n\nMiss Piggy is the ultimate diva, leading lady, fashion icon, star of stage, screen, and all media known and unknown in perpetuity throughout the universe. Miss Piggy has an appetite for the good things in life, including chocolate, jewelry, awards, and above all, her one true love, Kermit the Frog.\n\nKermit is the world’s most famous frog, but he has never let  international success go to his head. Arguably one of Jim Henson’s most famous Muppet creations, Kermit the Frog has come a long way from his home, the swamp, to become one of TV’s most beloved characters. \n\nMuppet Music Videos\nOnly on the official YouTube channel for The Muppets can you see the classic Muppets music videos, exclusive cuts of Muppets music, and all new original Muppets song covers! Check out classic Muppets music videos like The Muppets cover of Queen’s “Bohemian Rhapsody”  and The Muppets music videos for “Jungle Boogie”, as performed by Dr. Teeth and the Electric Mayhem. \n\nThe Muppets on YouTube\nWelcome to the Official YouTube channel for The Muppets! This channel is home to your beloved group of Muppet friends: Kermit the Frog, Miss Piggy, Fozzie Bear, Gonzo, Animal, Beaker, the Swedish Chef and more! Subscribe for some of your favorite and best film and television clips from The Muppets, as well as music covers and brand new comedy sketches.\n\nCheck out exclusive Muppet parodies, Muppet music videos, Muppet song covers, comedy sketches, and more! Join in the fun with original Muppet comedy shows, TV promos, and charity PSAs. Tune into the all new the Muppet show, “The Muppets” on Tuesday nights at 8|7c on ABC!'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='title',
            field=models.TextField(default='Bohemian Rhapsody | Muppet Music Video | The Muppets'),
        ),
    ]
