# Generated by Django 2.0.4 on 2018-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0006_auto_20180509_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='domain',
            field=models.CharField(default='Enter domain', max_length=20),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='description',
            field=models.TextField(default='Only change if you want to edit, Will fetch from youtube'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='time_to_show',
            field=models.TextField(default='Only change if you want to edit, Will fetch from youtube'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='title',
            field=models.TextField(default='Only change if you want to edit, Will fetch from youtube'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='video_id',
            field=models.TextField(default='8tPnX7OPo0Q', editable=False),
        ),
    ]
