# Generated by Django 2.0.5 on 2018-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0007_auto_20180614_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='thumbnail',
            field=models.TextField(default='https://i.ytimg.com/vi/tgbNymZ7vqY/maxresdefault.jpg'),
        ),
    ]
