# Generated by Django 2.0.5 on 2018-06-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0008_problemstatement_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='duration',
            field=models.TextField(default='4:20'),
        ),
        migrations.AlterField(
            model_name='problemstatementplaylist',
            name='playlist_url',
            field=models.CharField(help_text='In format: https://www.youtube.com/watch?v=ev2SkXJVAbA&list=PLOoogDtEDyvsBG38tzlj1Zkd0PLxgZwXV', max_length=100, unique=True),
        ),
    ]
