# Generated by Django 2.0.5 on 2018-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0009_auto_20180617_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='views',
            field=models.TextField(default='0'),
        ),
    ]
