# Generated by Django 2.0.5 on 2018-07-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0010_problemstatement_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='likes_number',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='time_number',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='views_number',
            field=models.TextField(default='0'),
        ),
    ]
