# Generated by Django 2.0.5 on 2018-07-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemstatements', '0011_auto_20180702_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='dislikes_number',
            field=models.TextField(default='0'),
        ),
    ]
