# Generated by Django 2.0.5 on 2018-05-23 18:55

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('is_participant', models.BooleanField(default=True)),
                ('is_mentor', models.BooleanField(default=False)),
                ('is_sponsor', models.BooleanField(default=False)),
                ('is_end_user', models.BooleanField(default=False)),
                ('contested_challenges', models.IntegerField(default=0)),
                ('mentored_challenges', models.IntegerField(default=0)),
                ('mentored_won_challenges', models.IntegerField(default=0)),
                ('sponsored_challenges', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
