# Generated by Django 2.0.5 on 2018-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
