# Generated by Django 2.0.5 on 2018-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mentored_challenges',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsored_challenges',
            field=models.IntegerField(default=1),
        ),
    ]
